name: Continuous Integration
on:
  pull_request:
  push:
    branches:
    - master

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    container: ${{matrix.container_image}}
    strategy:
      matrix:
        container_image: ['osrf/ros2:nightly-rmw-nonfree']

    steps:
    - name: Clone buildfarm_perf_tests
      uses: actions/checkout@v2
      with:
        path: src/buildfarm_perf_tests
    - name: Update, build, and test
      run: |
        echo ::group::Update packages
        apt-get update
        apt-get upgrade -y
        apt-get install -y python3-pip
        rosdep update
        echo ::endgroup::
        . /opt/ros/*/setup.sh
        echo ::group::Install dependencies
        rosdep install -y --from-path src --ignore-src --skip-keys 'performance_test'
        pip3 install flake8_builtins flake8_quotes
        echo ::endgroup::
        echo ::group::Build package
        colcon build --event-handler console_direct+ --cmake-args -DCMAKE_CXX_FLAGS=-Werror -Werror=dev -Werror=deprecated
        echo ::endgroup::
        echo ::group::Test package
        colcon test --event-handler console_direct+ --ctest-args --label-exclude performance
        echo ::endgroup::
        colcon test-result
